spring:
  profiles:
    include:
    - oauth
  application:
    name: club
  datasource:
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    url: jdbc:log4jdbc:mariadb://np.javaman.shop:3306/security
    # driver-class-name: org.mariadb.jdbc.Driver
    # url: jdbc:mariadb://np.javaman.shop:3306/guestbook
    username: sample
    password: 1234


  jpa:
    hibernate:
      ddl-auto: update # 배포할땐 이렇게하면 망할수 있으니 조심 (배포할때 끄기)
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
    show-sql: true # SQL 로그 출력
    database-platform: org.hibernate.dialect.MariaDBDialect



  devtools:
    restart:
      enabled: true
      additional-paths:
      - src/main/java
      - src/main/resources
      additional-exclude: static/**
    livereload:
      enabled: true
  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    suffix: .html
    encoding: UTF-8
    mode: html
  
  security:
    user:
      name: user1
      password: $2a$10$ZoY0NyBPXhblfzY210wrJePCBfGZH/baDYJNnA1MZN9GjwwGcbJki #1234
      roles:
      - USER
      